export const styles = {
  pageContainer: {
    fontFamily: "Roboto, sans-serif",
    backgroundColor: "#f5f6f8",
    minHeight: "100vh",
    padding: "20px",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
    padding: "10px 20px",
    borderRadius: "12px",
    boxShadow: "0 4px 10px rgba(0,0,0,0.08)",
    marginBottom: "20px",
  },
  headerCenter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
  },
  logo: { height: "50px", width: "50px" },
  appNameImage: { height: "32px", width: "128px" },
  navBar: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "10px",
  },
  newButton: {
    backgroundColor: "#3498db",
    color: "#fff",
    padding: "8px 16px",
    borderRadius: "8px",
    border: "none",
    cursor: "pointer",
  },
  navTitle: { fontWeight: 500, fontSize: "16px", marginLeft: "10px" },
  searchInput: {
    flex: 1,
    padding: "6px 12px",
    borderRadius: "8px",
    border: "1px solid #dcdde1",
  },
  tabRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "12px",
    flexWrap: "wrap",
  },
  tabItem: {
    padding: "6px 12px",
    borderRadius: "12px",
    fontSize: "14px",
  },
  tableContainer: {
    backgroundColor: "#fff",
    borderRadius: "12px",
    boxShadow: "0 4px 10px rgba(0,0,0,0.08)",
    padding: "10px",
    overflowX: "auto",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "14px",
  },
  th: {
    padding: "10px",
    textAlign: "left",
    borderBottom: "2px solid #ecf0f1",
    fontWeight: 600,
  },
  td: {
    padding: "10px",
    borderBottom: "1px solid #ecf0f1",
  },
  input: {
    padding: "6px 10px",
    borderRadius: "6px",
    border: "1px solid #dcdde1",
    width: "100%",
  },
  buttonPrimary: {
    backgroundColor: "#3498db",
    color: "#fff",
    padding: "8px 16px",
    borderRadius: "8px",
    border: "none",
    cursor: "pointer",
    marginLeft: "10px",
  },
  buttonSecondary: {
    backgroundColor: "#ecf0f1",
    color: "#2c3e50",
    padding: "6px 12px",
    borderRadius: "8px",
    border: "none",
    cursor: "pointer",
    marginLeft: "5px",
  },
  formGroup: {
    marginBottom: "12px",
    display: "flex",
    flexDirection: "column",
  },
};
