# Generated by Django 5.2.2 on 2025-09-20 14:18

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(db_index=True, help_text='Stock Keeping Unit', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('RAW', 'Raw Material'), ('FINISHED', 'Finished Good')], default='RAW', max_length=10)),
                ('stock_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=18)),
                ('unit_of_measure', models.CharField(help_text='e.g., units, kg, meters', max_length=50)),
                ('reorder_level', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=18)),
                ('default_warehouse', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sku',),
            },
        ),
        migrations.CreateModel(
            name='StockLedgerEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('INIT', 'Initial Stock'), ('IN', 'Stock In (Production)'), ('OUT', 'Stock Out (Consumption)'), ('ADJ', 'Manual Adjustment')], max_length=10)),
                ('quantity_changed', models.DecimalField(decimal_places=4, max_digits=18)),
                ('new_stock_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('notes', models.TextField(blank=True, help_text='e.g., MO-101 Consumption')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='inventory.product')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku', 'name'], name='inventory_p_sku_b86f20_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['product', 'transaction_type', 'created_at'], name='inventory_s_product_46223c_idx'),
        ),
    ]
